In [1]:
import torch

In [2]:
torch.__version__

'2.1.1'

In [3]:
torch.tensor(8)

tensor(8)

In [7]:
z = torch.zeros(2,3)

In [10]:
z.ndim

2

In [11]:
z.shape

torch.Size([2, 3])

In [12]:
z[0]

tensor([0., 0., 0.])

In [20]:
a = torch.tensor([[1.,2.],[3.,4.]])

In [21]:
a

tensor([[1., 2.],
        [3., 4.]])

In [22]:
b = torch.ones(2,1)

In [23]:
b

tensor([[1.],
        [1.]])

In [24]:
a @ b

tensor([[3.],
        [7.]])

In [28]:
torch.rand(3,2)

tensor([[0.6739, 0.4125],
        [0.0586, 0.2113],
        [0.8442, 0.3658]])

In [31]:
torch.arange(1,5,1.5)

tensor([1.0000, 2.5000, 4.0000])

In [42]:
a = torch.tensor([1,2,3])

In [43]:
a.dtype

torch.int64

In [44]:
a.type(torch.float32)

tensor([1., 2., 3.])

In [45]:
a.device

device(type='cpu')