In [2]:
import torch

In [3]:
torch.__version__

'2.1.1'

In [4]:
torch.cuda.is_available()

True

In [5]:
torch.tensor(8)

tensor(8)

In [6]:
z = torch.zeros(2,3)

In [7]:
z.ndim

2

In [8]:
z.shape

torch.Size([2, 3])

In [9]:
z[0]

tensor([0., 0., 0.])

In [10]:
a = torch.tensor([[1.,2.],[3.,4.]])

In [11]:
a

tensor([[1., 2.],
        [3., 4.]])

In [12]:
b = torch.ones(2,1)

In [13]:
b

tensor([[1.],
        [1.]])

In [14]:
a @ b

tensor([[3.],
        [7.]])

In [15]:
torch.rand(3,2)

tensor([[0.6545, 0.7914],
        [0.1999, 0.3197],
        [0.7415, 0.5952]])

In [16]:
torch.arange(1,5,1.5)

tensor([1.0000, 2.5000, 4.0000])

In [24]:
a = torch.tensor([1,2,3],dtype=torch.float32)

In [25]:
a.dtype

torch.float32

In [26]:
a.type(torch.float32)

tensor([1., 2., 3.])

In [27]:
a.device

device(type='cpu')

In [28]:
a.min()

tensor(1.)

In [29]:
a.max()

tensor(3.)

In [30]:
a.mean()

tensor(2.)

In [32]:
a.sum()

tensor(6.)

In [33]:
a.argmax()

tensor(2)

In [34]:
a.argmin()

tensor(0)

In [36]:
x = torch.arange(1.,10.)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [37]:
x = x.view(3,3)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [39]:
torch.stack([x,x,x],dim=0)

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [44]:
torch.hstack([x,x])

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [98]:
Weights = 3
biases = 2
X = torch.arange(1,20,0.2)
y = Weights * X + biases

In [99]:
# train test split
train_split = (int) (0.8 * len(X))
X_train,y_train = X[:train_split],y[:train_split]
X_test,y_test =  X[train_split:],y[train_split:]

In [107]:
# linear regression
W = 1
b = 1
lr = 0.001
y_pred = W * X_train + b
loss = ((y_pred - y_train)**2).mean()
print(loss)
for i in range(5000):
    y_pred = W * X_train + b
    loss =  ((y_pred - y_train)**2).mean()
    dL_dw = (2*(y_pred-y_train) *  X_train).mean()
    dL_db =  (2*(y_pred-y_train)).mean()
    W-= lr * dL_dw
    b-= lr*dL_db
print(loss)

tensor(401.)
tensor(0.0021)


In [108]:
W,b

(tensor(3.0093), tensor(1.8998))

In [109]:
y_pred = W * X_test + b
loss = ((y_pred - y_test)**2).mean()
loss

tensor(0.0047)

In [182]:
class LinearRegression(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.weights = torch.nn.Parameter(torch.randn(1,requires_grad=True,dtype=torch.float))
        self.bias = torch.nn.Parameter(torch.randn(1,requires_grad=True,dtype=torch.float))
    def forward(self,x:torch.Tensor) ->torch.Tensor:
        return self.weights * x + self.bias

In [199]:
model = LinearRegression()
model.state_dict()

OrderedDict([('weights', tensor([0.7797])), ('bias', tensor([-0.6762]))])

In [200]:
with torch.inference_mode():
    out = model(X_test)
out

tensor([11.9551, 12.1110, 12.2670, 12.4229, 12.5788, 12.7348, 12.8907, 13.0467,
        13.2026, 13.3585, 13.5145, 13.6704, 13.8264, 13.9823, 14.1383, 14.2942,
        14.4501, 14.6061, 14.7620])

In [204]:
loss_fn = torch.nn.L1Loss()
lr = 0.01
opt = torch.optim.Adam(params=model.parameters(),lr=lr)

In [209]:
epochs=2001

for epoch in range(epochs):
    model.train()

    y_pred= model(X_train)

    loss = loss_fn(y_pred,y_train)

    opt.zero_grad()

    loss.backward()

    opt.step()

    if epoch % 100 == 0:
        with torch.inference_mode():
            y_pred = model(X_test)
            test_loss = loss_fn(y_pred,y_test)
            print(f"Epoch : {epoch} Loss : {loss} Validation Loss : {test_loss}")

Epoch : 0 Loss : 0.018030203878879547 Validation Loss : 0.03230687230825424
Epoch : 100 Loss : 0.023385368287563324 Validation Loss : 0.04224375635385513
Epoch : 200 Loss : 0.018030203878879547 Validation Loss : 0.03230687230825424
Epoch : 300 Loss : 0.023385368287563324 Validation Loss : 0.04224375635385513
Epoch : 400 Loss : 0.018030203878879547 Validation Loss : 0.03230687230825424
Epoch : 500 Loss : 0.023385368287563324 Validation Loss : 0.04224375635385513
Epoch : 600 Loss : 0.018030203878879547 Validation Loss : 0.03230687230825424
Epoch : 700 Loss : 0.023385368287563324 Validation Loss : 0.04224375635385513
Epoch : 800 Loss : 0.018030203878879547 Validation Loss : 0.03230687230825424
Epoch : 900 Loss : 0.023385368287563324 Validation Loss : 0.04224375635385513
Epoch : 1000 Loss : 0.018030203878879547 Validation Loss : 0.03230687230825424
Epoch : 1100 Loss : 0.023385368287563324 Validation Loss : 0.04224375635385513
Epoch : 1200 Loss : 0.018030203878879547 Validation Loss : 0.032

In [208]:
model.state_dict()

OrderedDict([('weights', tensor([2.9981])), ('bias', tensor([1.9984]))])